export const categories = [
  { id: 'namkeen', en: 'Namkeen & snacks', hi: 'नमकीन एवं स्नैक्स', short: 'Namkeen', index: 0, note: 'A little crunch for every day.' },
  { id: 'chips', en: 'Banana chips', hi: 'केला चिप्स', short: 'Banana chips', index: 1, note: 'Golden, crisp and full of flavour.' },
  { id: 'bakery', en: 'Biscuits & bakery', hi: 'बिस्किट एवं बेकरी', short: 'Bakery', index: 2, note: 'Little joys for your tea time.' },
  { id: 'papad', en: 'Papad & khakhra', hi: 'पापड़ एवं खाखरा', short: 'Khakhra', index: 3, note: 'Crisp companions to your meals.' },
  { id: 'other', en: 'More to munch', hi: 'दाने एवं अन्य', short: 'More snacks', index: 4, note: 'Something for every craving.' },
  { id: 'pantry', en: 'Flour & spices', hi: 'आटा एवं मसाले', short: 'Pantry', index: 5, note: 'Everyday essentials, thoughtfully made.' },
];

const rows = [
 ['namkeen','hand-sev','Hand Sev','हाथ की सेव',300,'kg'],
 ['namkeen','hand-papdi','Hand Papdi','हाथ की पपड़ी',300,'kg'],
 ['namkeen','plain-papdi','Plain Papdi','फीकी पपड़ी',300,'kg'],
 ['namkeen','sweet-mixture','Sweet Mixture','मीठा मिक्सचर',300,'kg'],
 ['namkeen','spicy-mixture','Spicy Mixture','चरखा मिक्सचर',300,'kg'],
 ['namkeen','spicy-nukti','Spicy Nukti','चरखी नुक्ती',300,'kg'],
 ['namkeen','gathiya','Gathiya','गाठिये',300,'kg'],
 ['namkeen','burhanpuri-gathiya','Burhanpuri Gathiya','बुरहानपुरी गाठिये',300,'kg'],
 ['namkeen','mogar','Mogar','मोगर',300,'kg'],
 ['namkeen','chana-dal','Chana Dal','चने की दाल',300,'kg'],
 ['namkeen','chana-dal-dhaniya','Chana Dal Dhaniya','चने की दाल धनिया',300,'kg'],
 ['namkeen','masoor','Masoor','मसूर',300,'kg'],
 ['namkeen','soya-sticks','Soya Sticks','सोया स्टिक',300,'kg'],
 ['chips','pepper-banana-chips','Black Pepper Banana Chips','काली मिर्च केला चिप्स',300,null],
 ['chips','chilli-banana-chips','Red Chilli Banana Chips','लाल मिर्च केला चिप्स',300,null],
 ['chips','mint-banana-chips','Mint Banana Chips','पुदीना केला चिप्स',300,null],
 ['chips','tomato-banana-chips','Tomato Banana Chips','टमाटर केला चिप्स',300,null],
 ['chips','sweet-banana-mixture','Sweet Banana Mixture','केला मीठा मिक्सचर',320,null],
 ['chips','spicy-banana-mixture','Spicy Banana Mixture','केला चरखा मिक्सचर',320,null],
 ['other','pepper-peanuts','Black Pepper Peanuts','काली मिर्च दाने',320,null],
 ['other','chilli-peanuts','Red Chilli Peanuts','लाल मिर्च दाने',320,null],
 ['other','sendha-peanuts','Sendha Salt Peanuts','सांदे नमक दाने',280,null],
 ['other','mangodi','Mangodi Saloni','मंगोड़ी सलोनी',275,null],
 ['other','atta-chakli','Atta Chakli','आटा चकली',275,null],
 ['other','sweet-khurme','Sweet Khurme','मीठे खुर्मे',275,null],
 ['other','shakkar-para','Shakkar Pare','शक्कर पारे',275,null],
 ['other','mini-samosa','Mini Samosa','छोटे समोसे',275,null],
 ['other','mini-kachori','Mini Kachori','छोटी कचौरी',275,null],
 ['other','tasty-peanuts','Tasty Peanuts','टेस्टी दाने',320,null],
 ['bakery','cashew-biscuits','Cashew Biscuits','काजू बिस्कुट',30,null],
 ['bakery','sweet-atta-biscuits','Sweet Atta Biscuits','मीठा आटा बिस्कुट',400,null],
 ['bakery','jeera-atta-biscuits','Jeera Atta Biscuits','जीरा आटा बिस्कुट',400,null],
 ['bakery','ajwain-atta-biscuits','Ajwain Atta Biscuits','अजवाइन आटा बिस्कुट',400,null],
 ['bakery','dry-fruit-biscuits','Dry Fruit Biscuits','ड्राई फ्रूट बिस्कुट',500,null],
 ['bakery','atta-toast','Atta Toast','आटा टोस्ट',300,null],
 ['bakery','cream-roll','Cream Roll','क्रीम रोल',140,null],
 ['bakery','pav','Pav','पाव',70,'dozen'],
 ['bakery','atta-bread','Atta Bread','आटा ब्रेड',70,null],
 ['bakery','pizza-base','Pizza Base','पिज़्ज़ा बेस',30,null],
 ['bakery','atta-cupcake','Atta Cupcake','आटा कप केक',90,null],
 ['papad','moong-papad','Moong Papad','मूंग पापड़',240,null],
 ['papad','chana-papad','Chana Papad','चना पापड़',240,null],
 ['papad','plain-khakhra','Plain Khakhra','खाखरा सादा',60,'packet'],
 ['papad','jeeravan-khakhra','Jeeravan Khakhra','खाखरा जीरावन',60,'packet'],
 ['papad','ajwain-khakhra','Ajwain Khakhra','खाखरा अजवाइन',60,'packet'],
 ['pantry','salt','Salt','नमक',60,null],
 ['pantry','chilli','Ground Chilli','मिर्च',500,null],
 ['pantry','coriander','Ground Coriander','धना',300,null],
 ['pantry','turmeric','Ground Turmeric','हल्दी',500,null],
 ['pantry','maida','Maida','मैदा',60,null],
 ['pantry','rava','Rava','रवा',60,null],
 ['pantry','thuli','Thuli','थुली',70,null],
];

const descriptions = {
 namkeen: ['A familiar Indori crunch, made in our own facility. Choose your favourite from our namkeen range.', 'हमारी अपनी इकाई में तैयार नमकीन। अपने पसंदीदा स्वाद को चुनें।'],
 chips: ['Explore the flavours in our banana chips range. Ask us about the available pack sizes.', 'केला चिप्स के अलग-अलग स्वाद। पैक की जानकारी के लिए हमसे संपर्क करें।'],
 bakery: ['Biscuits, breads and tea-time treats from our own facility in Indore.', 'इंदौर की हमारी अपनी इकाई के बिस्किट, ब्रेड और बेकरी उत्पाद।'],
 papad: ['A crisp addition to your everyday meals. Discover our papad and khakhra range.', 'रोज़ के भोजन के लिए पापड़ और खाखरा की हमारी रेंज।'],
 other: ['Explore our savoury and sweet snacks for everyday snacking.', 'रोज़ के लिए हमारे नमकीन और मीठे स्नैक्स की रेंज।'],
 pantry: ['Explore the flour and spice essentials on our product list.', 'हमारी सूची में उपलब्ध आटा और मसाले।'],
};

export const seedProducts = rows.map(([category,id,nameEn,nameHi,price,unit],i) => ({
 id, category, nameEn, nameHi, descriptionEn: descriptions[category][0], descriptionHi: descriptions[category][1],
 status: 'published', available: true, featured: ['hand-sev','plain-khakhra','jeera-atta-biscuits','pepper-banana-chips'].includes(id),
 image: '', imageIllustrative: true, national: category === 'namkeen' || id.includes('biscuits'),
 ingredients: '', ingredientsVerified: false, dairy: 'unconfirmed', shelfLife: '', storage: '',
 seasonal: false, priceUnitConfirmed: !!unit, position: i,
 packs: [{ id:'standard', labelEn:unit === 'kg' ? '1 kg' : unit === 'dozen' ? '1 dozen' : unit === 'packet' ? '1 packet' : 'Pack details to confirm', labelHi:unit === 'kg' ? '1 किलो' : unit === 'dozen' ? '1 दर्जन' : unit === 'packet' ? '1 पैकेट' : 'पैक की पुष्टि बाकी', unit:unit || '', price, sale:null }],
}));

export const seedSettings = {
 name:'Jain Shudh Snacks', phone:'8982819979', address:'187 B Anjani Nagar, Airport Road, near Malwa Hospital, Indore',
 hours:'', fssai:'', gst:'', announcementEn:'Made in Indore. Prepared with care.', announcementHi:'इंदौर में तैयार। देखभाल के साथ।',
 orderIssuePolicy:'',
};
